name: SPLExample
version: '${project.version}'
main: net.willowmc.splexample.SPLExample
api-version: 1.20
authors: [ jesus_is_hot ]
depend: [ SimplePluginLibrary ]
description: Example plugin using SimplePluginLibrary.
